### ISSUE TITLE
Bot not working or help needed

### ISSUE THREAD

**Issue by drapic** [FKLC/MentionRedirector#2]
Hello!

I am having the problem, where the bot doesnt move messages to channels.

The command "r!to #channel last_10_messages" means that it should forward last 10 messages to the channel named "channel", am i right?
When i write that into the channel, the bot isnt responding, and its not forwarding messages.
Redirector role has complete access to both channels.
r!help is working, and pinging someone is automatically DM-ing the person with the notification

Please help and thanks in advance!

P.S. Can i command the bot, to forward ALL messages that come into the channel, into private one?

**Comment by FKLC** [comment]
I tried it just now, and for some reason it didn't work for me too. Then I kicked the bot and invited it back and it started working again. Unfortunately I have no clue why it wasn't working though. I tried removing its permissions and trying again but then it would still redirect messages but wouldn't delete the old ones. So, as I've said I have no clue why it wasn't working but kicking and inviting it back should work.

**Comment by drapic** [comment]
Hey!

Thank you for quick response.

I have already kicked the bot out, but what is not working is "last_n_messages".

What i found that is working for me is, instead of "last_n_messages", just write "n", example: "r!to #channel 5" instead of "r!to #channel last_5_messages"

Thanks again!

Kind Regards,
Sadin Drapic
